Eval2/EX_NFL/core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns = [

    ##urls estadio 
    path('lista/estadio/',views.listaestadios.as_view(), name="listaestadio"),
    path('crear/estadio/',views.Createestadio.as_view(), name="crearestadio"),
    path('recuperar/estadio/<int:pk>/', views.Detailestadio.as_view(), name= "recestadio"),
    path('actualizar/estadio/<int:pk>/', views.Updateestadio.as_view(), name= "actuestadio"),
    path('borrar/estadio/<int:pk>/', views.Deleteestadio.as_view(), name= "delestadio"),

    ##urls equipo
    path('lista/equipo/',views.Listaequipos.as_view(), name="listaequipo"),
    path('crear/equipo/',views.Createequipos.as_view(), name="crearequipo"),
    path('recuperar/equipo/<int:pk>/', views.Detailequipos.as_view(), name= "recequipo"),
    path('actualizar/equipo/<int:pk>/', views.Updateequipos.as_view(), name= "actuequipo"),
    path('borrar/equipo/<int:pk>/', views.Deleteequipos.as_view(), name= "delequipo"),

    ##urls ciudad
    path('lista/ciudad/',views.listaciudades.as_view(), name="listaciudad"),
    path('crear/ciudad/',views.Createcuidad.as_view(), name="crearciudad"),
    path('recuperar/ciudad/<int:pk>/', views.Detailciudad.as_view(), name= "recuciudad"),
    path('actualizar/ciudad/<int:pk>/', views.Updateciudad.as_view(), name= "actuciudad"),
    path('borrar/ciudad/<int:pk>/', views.Deleteciudad.as_view(), name= "delciudad"),
]

Eval2/EX_NFL/ex_nfl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))
]

Eval2/EX_NFL/home/urls.py
from django.urls import path, include
from home import views

app_name="home"
urlpatterns = [
   path('', views.inicio.as_view(),name='inicio') 
]

Eval2/EX_NFL/core/models.py
from django.db import models

# Create your models here.

class Ciudades(models.Model):
    Nombre = models.CharField(max_length=35, default= "Ciudad")
    def __str__(self):
        return self.Nombre

class Equipos(models.Model):
    Nombre = models.CharField(max_length=35, default= "Tuequipo")
    Ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    def __str__(self):
        return self.Nombre

class Estadios(models.Model):
    Nombre = models.CharField(max_length=35)
    Equipos= models.ForeignKey(Equipos, on_delete=models.CASCADE)
    def __str__(self):
        return self.Nombre

Eval2/EX_NFL/home/models.py
from django.db import models

# Create your models here.

Eval2/EX_NFL/core/forms.py
from django import forms
from .models import *

##estadios

class estadiosforms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            }



class actulizarestadiosforms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            }

##equpos

class equipoforms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            }
        
class actualizarequiposforms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            }

##ciudad

class ciudadesforms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }

class actualizarciudadesforms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }

Eval2/EX_NFL/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *



# Create your views here.

##STADIOS

class listaestadios(generic.View):
    template_name = "core/estadio/listaestadio.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Estadio = Estadios.objects.all()
        self.context = {
            "Estadios": Estadio
        }
        return render(request, self.template_name,self.context)


class Detailestadio(generic.DetailView):
    template_name = "core/estadio/recestadio.html"
    model = Estadios


class Createestadio(generic.CreateView):
    template_name = "core/estadio/crearestadio.html"
    model = Estadios
    form_class = estadiosforms
    success_url = reverse_lazy("core:listaestadio")


class Updateestadio(generic.UpdateView):
    template_name = "core/estadio/actuestadio.html"
    model = Estadios
    form_class = actulizarestadiosforms
    success_url = reverse_lazy("core:listaestadio")

class Deleteestadio(generic.DeleteView):
    template_name = "core/estadio/delestadio.html"
    model = Estadios
    success_url = reverse_lazy("core:listaestadio")


#Equipos

class Listaequipos(generic.View):
    template_name = "core/equipo/listaequipo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipo =  Equipos.objects.all()
        self.context = {
            "Equipos": equipo
        }
        return render(request, self.template_name,self.context)
    
class Createequipos(generic.CreateView):
    template_name = "core/equipo/crearequipo.html"
    model = Equipos
    form_class = equipoforms
    success_url = reverse_lazy("core:listaequipo")

class Detailequipos(generic.DetailView):
    template_name = "core/equipo/recequipo.html"
    model = Equipos

class Updateequipos(generic.UpdateView):
    template_name = "core/equipo/actuequipo.html"
    model = Equipos
    form_class = actualizarequiposforms
    success_url = reverse_lazy("core:listaequipo")

class Deleteequipos(generic.DeleteView):
    template_name = "core/equipo/delequipo.html"
    model = Equipos
    success_url = reverse_lazy("core:listaequipo")

#Ciudad 

class listaciudades(generic.View):
    template_name = "core/ciudad/listaciudad.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Ciudad = Ciudades.objects.all()
        self.context = {
            "Ciudades": Ciudad
        }
        return render(request, self.template_name,self.context)

class Createcuidad(generic.CreateView):
    template_name = "core/ciudad/crearciudad.html"
    model = Ciudades
    form_class = ciudadesforms
    success_url = reverse_lazy("core:listaciudad")

class Detailciudad(generic.DetailView):
    template_name = "core/ciudad/recciudad.html"
    model = Ciudades

class Updateciudad(generic.UpdateView):
    template_name = "core/ciudad/actciudad.html"
    model = Ciudades
    form_class = actualizarciudadesforms
    success_url = reverse_lazy("core:listaciudad")

class Deleteciudad(generic.DeleteView):
    template_name = "core/ciudad/delciudad.html"
    model = Ciudades
    success_url = reverse_lazy("core:listaciudad")

Eval2/EX_NFL/home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
class inicio(generic.View):
    template_name = "home/inicio.html"
    context={}
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

Eval2/EX_NFL/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">NFL</a>
      <img src="nfl.jpg" width="50" height="40" /> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaequipo' %}">Equipos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaciudad' %}">Ciudades</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaestadio' %}">Estadios</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-dark" href="https://www.nfl.com/">NFL.com</a>
    </div>
    <!-- Copyright -->
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

Eval2/EX_NFL/templates/core/ciudad/actciudad.html
{% extends "base/base.html" %}

{% block title %}
Actualizar ciudad
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar ciudad</button>
        <a href="{% url 'core:listaciudad' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/ciudad/crearciudad.html
{% extends "base/base.html" %}

{% block title %}
Crear una cuidad
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear una ciudad</button>
        <a href="{% url 'core:listaciudad' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/ciudad/delciudad.html
{% extends "base/base.html" %}

{% block title %}
Borrar ciudad
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Seguro de borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Borrar ciudad</button>
        <a href="{% url 'core:listaciudad' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/ciudad/listaciudad.html
{% extends 'base/base.html' %}

{% block title %} LIST OF CITYS {% endblock title %}

{% block content %}


    <a href="{% url 'core:crearciudad' %}" class="btn btn-outline-success form-control">Crear nueva ciudad</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th></th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for ciudad in ciudad %}
                <tr>
                    <td>{{ Ciudades.id }}</td>
                    <td>{{ Ciudades.Nombre }}</td>
                    <td><a href="{% url 'core:recciudad' Ciudades.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:actciudad' Ciudades.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:delciudad' Ciudades.id %}" class="btn btn-outline-danger">Borrar</a></td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
   
   <br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock content %}

Eval2/EX_NFL/templates/core/ciudad/recciudad.html
{% extends "base/base.html" %}

{% block title %}
Detalles de la ciudad
{% endblock title %}


{% block content %}
<h1>Nombre: </h1>{{ object.Nombre }}
<br>
<h1>ID: </h1>{{ object.id }}
  <a href="{% url 'core:listaciudad' %}">Regresar</a>
{% endblock content %}

Eval2/EX_NFL/templates/core/equipo/actequipo.html
{% extends "base/base.html" %}

{% block title %}
Actualizar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/equipo/crearequipo.html
{% extends "base/base.html" %}

{% block title %}
Crear un equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/equipo/delquipo.html
{% extends "base/base.html" %}

{% block title %}
Borrar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Seguro de borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Borrar equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/equipo/listaequipo.html
{% extends 'base/base.html' %}

{% block title %} Lista de Equipos
{% endblock title %}

{% block content %}


    <a href="{% url 'core:crearequipo' %}" class="btn btn-outline-success form-control">Crear un nuevo equipo</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th></th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for equipo in equipo %}
                <tr>
                    <td>{{ Equipos.id }}</td>
                    <td>{{ Equipos.Nombre }}</td>
                    <td><a href="{% url 'core:recequipo' Equipos.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:actequipo' Equipos.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:delequipo' Equipos.id %}" class="btn btn-outline-danger">Borrar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

Eval2/EX_NFL/templates/core/equipo/recequipo.html
{% extends "base/base.html" %}

{% block title %}
Detalles del equipo
{% endblock title %}


{% block content %}
<h1>Nombre: </h1>{{ object.Nombre }}
<br>
<h1>Ciudad: </h1>{{ object.Ciudad }}
  <a href="{% url 'core:listaequipo' %}">Regresar</a>
{% endblock content %}

Eval2/EX_NFL/templates/core/estadio/actestadio.html
{% extends "base/base.html" %}

{% block title %}
Actualizar estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar estadios</button>
        <a href="{% url 'core:listaestadio' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/estadio/crearestadio.html
{% extends "base/base.html" %}

{% block title %}
Crear estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear estadio</button>
        <a href="{% url 'core:listaestadio' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/estadio/delestadio.html
{% extends "base/base.html" %}

{% block title %}
Borrar estadio
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Seguro de borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Borrar estadio</button>
        <a href="{% url 'core:listaestadio' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

Eval2/EX_NFL/templates/core/estadio/listaestadio.html
{% extends 'base/base.html' %}

{% block title %} 
Lista de estdios 
{% endblock title %}

{% block content %}


    <a href="{% url 'core:crearestadio' %}" class="btn btn-outline-success form-control">Nuevo estadio</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th></th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for estadio in estadio %}
                <tr>
                    <td>{{ Estadios.id }}</td>
                    <td>{{ Estadios.Nombre }}</td>
                    <td><a href="{% url 'core:recestadio' Estadios.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:actestadio' Estadios.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:destadio' Estadios.id %}" class="btn btn-outline-danger">Borrar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

Eval2/EX_NFL/templates/core/estadio/recestadio.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del estadio
{% endblock title %}


{% block content %}
<h1>Nombre: </h1>{{ object.Nombre }}
<br>
<h1>Equipo: </h1>{{ object.Equipos }}
  
  <a href="{% url 'core:listaestadio' %}">Voler</a>
{% endblock content %}

Eval2/EX_NFL/templates/home/inicio.html
{% extends "base/base.html" %}
{% block title %}inicio view{% endblock title %}

{%block content%}
texto de explicacion

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
 
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>

{%endblock content%}